/**
 * Parameter and result types for every A2A-Swap SDK operation.
 * All token amounts are native `bigint` (atomic units).
 */

import type { PublicKey } from '@solana/web3.js';

// ─── Input parameters ─────────────────────────────────────────────────────────

/** Parameters for {@link A2ASwapClient.createPool}. */
export interface CreatePoolParams {
  /** First token mint — defines "token A" in the pool PDA seed. */
  mintA: PublicKey;
  /** Second token mint — defines "token B" in the pool PDA seed. */
  mintB: PublicKey;
  /**
   * LP fee in basis points. Range: 1–100 (0.01%–1.00%).
   * Typical: `30` (0.30%).
   */
  feeRateBps: number;
}

/** Parameters for {@link A2ASwapClient.provideLiquidity}. */
export interface ProvideParams {
  /** First token mint — must match the pool's `tokenAMint`. */
  mintA: PublicKey;
  /** Second token mint — must match the pool's `tokenBMint`. */
  mintB: PublicKey;
  /** Amount of token A to deposit (atomic units). */
  amountA: bigint;
  /**
   * Amount of token B to deposit.
   * - `undefined` when the pool has liquidity: SDK auto-computes proportionally.
   * - Set explicitly for the first deposit (this sets the initial price).
   */
  amountB?: bigint;
  /** Re-invest accrued fees into LP shares instead of claiming them. Default: `false`. */
  autoCompound?: boolean;
  /**
   * Minimum combined fee balance before auto-compound fires.
   * `0n` means compound every time fees are claimed. Default: `0n`.
   */
  compoundThreshold?: bigint;
  /** Minimum LP shares to accept. `0n` = no slippage guard. Default: `0n`. */
  minLp?: bigint;
}

/** Parameters for {@link A2ASwapClient.convert}. */
export interface SwapParams {
  /** Mint of the token you are selling. */
  mintIn: PublicKey;
  /** Mint of the token you want to receive. */
  mintOut: PublicKey;
  /** Amount to sell (atomic units). */
  amountIn: bigint;
  /**
   * Maximum acceptable slippage in basis points (e.g. `50` = 0.5%).
   * `0` disables the slippage guard. Default: `50`.
   */
  maxSlippageBps?: number;
}

/** Parameters for {@link A2ASwapClient.simulate}. */
export interface SimulateParams {
  /** Mint of the token you would sell. */
  mintIn: PublicKey;
  /** Mint of the token you would receive. */
  mintOut: PublicKey;
  /** Amount to simulate selling (atomic units). */
  amountIn: bigint;
}

// ─── Result types ─────────────────────────────────────────────────────────────

/** Result of {@link A2ASwapClient.createPool}. */
export interface CreatePoolResult {
  /** Confirmed transaction signature. */
  signature: string;
  /** On-chain pool PDA address. */
  pool: PublicKey;
  /** Pool authority PDA that owns the token vaults. */
  poolAuthority: PublicKey;
  /** Token A vault (generated by this call). */
  vaultA: PublicKey;
  /** Token B vault (generated by this call). */
  vaultB: PublicKey;
  mintA: PublicKey;
  mintB: PublicKey;
  feeRateBps: number;
}

/** Result of {@link A2ASwapClient.provideLiquidity}. */
export interface ProvideResult {
  /** Confirmed transaction signature. */
  signature: string;
  /** Pool that received the deposit. */
  pool: PublicKey;
  /** Agent's position account (created on first deposit, updated thereafter). */
  position: PublicKey;
  /** Actual token A deposited (pool's token_a_mint amount). */
  amountA: bigint;
  /** Actual token B deposited (may differ if proportionally computed). */
  amountB: bigint;
}

/** Result of {@link A2ASwapClient.convert}. */
export interface SwapResult {
  /** Confirmed transaction signature. */
  signature: string;
  /** Pool used for the swap. */
  pool: PublicKey;
  /** Tokens sold. */
  amountIn: bigint;
  /** Pre-flight simulation estimate of tokens received. */
  estimatedOut: bigint;
  /** Minimum tokens the on-chain program would accept (slippage guard). */
  minAmountOut: bigint;
  /** `true` = token A → token B; `false` = token B → token A. */
  aToB: boolean;
}

/** Full fee and slippage breakdown from {@link A2ASwapClient.simulate}. */
export interface SimulateResult {
  /** Pool used for the simulation. */
  pool: PublicKey;
  /** `true` = token A → token B; `false` = token B → token A. */
  aToB: boolean;
  /** Input amount (atomic units). */
  amountIn: bigint;
  /** Protocol fee skimmed (0.020%, sent to treasury). */
  protocolFee: bigint;
  /** `amountIn - protocolFee` — gross amount received by the pool. */
  netPoolInput: bigint;
  /** LP fee deducted from `netPoolInput` (stays in vault, accrues to LPs). */
  lpFee: bigint;
  /** `netPoolInput - lpFee` — amount that moves the AMM curve. */
  afterFees: bigint;
  /** Expected output from the constant-product formula. */
  estimatedOut: bigint;
  /** `estimatedOut / amountIn` — effective exchange rate (raw units). */
  effectiveRate: number;
  /**
   * Pure AMM slippage: `afterFees / (reserveIn + afterFees) × 100`.
   * Does not include fee cost.
   */
  priceImpactPct: number;
  /** LP fee rate of this pool (basis points). */
  feeRateBps: number;
  /** Input-side vault reserve (atomic units). */
  reserveIn: bigint;
  /** Output-side vault reserve (atomic units). */
  reserveOut: bigint;
}

/** Pool state snapshot from {@link A2ASwapClient.poolInfo}. */
export interface PoolInfo {
  /** Pool PDA address. */
  pool: PublicKey;
  mintA: PublicKey;
  mintB: PublicKey;
  vaultA: PublicKey;
  vaultB: PublicKey;
  /** Token A reserve (atomic units). */
  reserveA: bigint;
  /** Token B reserve (atomic units). */
  reserveB: bigint;
  /** Total LP shares outstanding. */
  lpSupply: bigint;
  /** Trading fee rate (basis points). */
  feeRateBps: number;
  /** Spot price: `reserveB / reserveA` in raw atomic units. `0` when pool is empty. */
  spotPrice: number;
}

/** Single LP position from {@link A2ASwapClient.myPositions} / {@link A2ASwapClient.myFees}. */
export interface PositionInfo {
  /** On-chain position PDA address. */
  address: PublicKey;
  /** Pool this position belongs to. */
  pool: PublicKey;
  /** Owner of this position. */
  owner: PublicKey;
  /** LP shares held by this position. */
  lpShares: bigint;
  /** Fees stored on-chain from the last sync. */
  feesOwedA: bigint;
  feesOwedB: bigint;
  /** Fees accrued since the last on-chain sync (computed off-chain). */
  pendingFeesA: bigint;
  pendingFeesB: bigint;
  /** `feesOwedA + pendingFeesA` — total claimable now. */
  totalFeesA: bigint;
  /** `feesOwedB + pendingFeesB` — total claimable now. */
  totalFeesB: bigint;
  autoCompound: boolean;
  compoundThreshold: bigint;
}

/** Parameters for {@link A2ASwapClient.removeLiquidity}. */
export interface RemoveLiquidityParams {
  /** First token mint of the pool. */
  mintA: PublicKey;
  /** Second token mint of the pool. */
  mintB: PublicKey;
  /** Number of LP shares to burn. */
  lpShares: bigint;
  /** Minimum token A to accept (slippage guard). `0n` = no guard. Default: `0n`. */
  minA?: bigint;
  /** Minimum token B to accept (slippage guard). `0n` = no guard. Default: `0n`. */
  minB?: bigint;
}

/** Result of {@link A2ASwapClient.removeLiquidity}. */
export interface RemoveLiquidityResult {
  /** Confirmed transaction signature. */
  signature: string;
  /** Pool the shares were removed from. */
  pool: PublicKey;
  /** Agent's position account. */
  position: PublicKey;
  /** LP shares burned. */
  lpShares: bigint;
  /** Pre-flight estimate of token A returned. */
  expectedA: bigint;
  /** Pre-flight estimate of token B returned. */
  expectedB: bigint;
}

/** Result of {@link A2ASwapClient.claimFees}. */
export interface ClaimFeesResult {
  /** Confirmed transaction signature. */
  signature: string;
  /** Pool the fees were claimed from. */
  pool: PublicKey;
  /** Agent's position account. */
  position: PublicKey;
  /** Fees claimed / compounded for token A. */
  feesA: bigint;
  /** Fees claimed / compounded for token B. */
  feesB: bigint;
  /** `true` = fees were auto-compounded into LP shares. */
  autoCompound: boolean;
}

/** Aggregated fee summary from {@link A2ASwapClient.myFees}. */
export interface FeeSummary {
  positions: PositionInfo[];
  /** Sum of `totalFeesA` across all positions. */
  totalFeesA: bigint;
  /** Sum of `totalFeesB` across all positions. */
  totalFeesB: bigint;
}
